#Choose base image for Node js(node:18)
FROM node:18

#Set the Work Directory 
WORKDIR /app

#Copy the files to the current directory
COPY . .

#CMD Which is used to start the Node js
CMD ["node", "app.js"]
