#Choose base image for java app (node:18)
FROM node:18

#Set the Work Directory 
WORKDIR /app

#Copy the files to the current directory
COPY . .

#CMD Which is used to start the app
CMD ["node", "app.js"]
